// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package shorturl

import (
	"shortURL/config"
	"shortURL/internal/delivery/http"
	"shortURL/pkg/repository/mysql/database"
	"shortURL/pkg/repository/redis"
	"shortURL/pkg/service"
	"shortURL/pkg/wireset"
)

// Injectors from wire.go:

func Initialize() (Application, error) {
	configConfig, err := config.New()
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	cache, err := redis.InitRedisClient(configConfig)
	if err != nil {
		return Application{}, err
	}
	databaseDatabase, err := database.InitConnections(configConfig)
	if err != nil {
		return Application{}, err
	}
	shortURL := service.New(cache, databaseDatabase)
	httpServer := http.NewHttpServer(shortURL, cache)
	application := newApplication(logger, configConfig, httpServer)
	return application, nil
}
