version: '3.1'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: local
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
