logger:
  level: INFO
  format: console # json, console

http:
  port: 8080

mysql:
  dsn: "test:test@tcp(localhost:3306)/local?charset=utf8mb4&parseTime=True&loc=Local"

shorturl:
  expire_time : 1000

redis:
  cluster_mode: false
  host: "localhost"
  port: 6379
  password:
  max_retries: 1
  pool_size_per_node: 2
  db: 2
  dial_timeout: 15s
  expire_time: 24h