// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package migrate

import (
	"shortURL/config"
	"shortURL/pkg/repository/mysql/database"
	"shortURL/pkg/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configConfig, err := config.New()
	if err != nil {
		return Application{}, err
	}
	databaseDatabase, err := database.InitConnections(configConfig)
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	application := newApplication(configConfig, databaseDatabase, logger)
	return application, nil
}
